name: Déploiement Azure Streamlit

on:
  push:
    branches:
      - main  # change si tu déploies depuis une autre branche

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Déploiement sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.ASSIAAPPSERVICE }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9ACAFC67E80E487BBB138D4165EF91F5 }}
          package: .
